name: Black for formatting

on:
  push:
    branches: [i190555]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install black
        run: pip install black
      - uses: psf/black@stable
